// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btreedncazikewdjkadj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0cmVlZG5jYXppa2V3ZGprYWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDAxMDAsImV4cCI6MjA2NTUxNjEwMH0.WEerRJ9NJq78CpK5mOCKwi8_mKpslxMaCPyYQj6Roz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);